project:
  type: website
  resources:
    - CNAME

execute:
  freeze: true
  cache: true

website:
  title: "Colin Hill"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about/about.qmd
        text: About
      - icon: github
        href: https://github.com/colinahill/
      - icon: linkedin
        href: https://www.linkedin.com/in/colinahill/
  favicon: favicon.ico
  site-url: https://colinahill.com/
  google-analytics:
    tracking-id: "G-838Z23X56N"
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


