[project]
name = "website"
description = "Colin Hill's personal website"
authors = ["Colin Hill <colinalastairhill@gmail.com>"]
channels = ["conda-forge"]
# linux-64 is used by GitHub Actions
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "==3.11"
jupyter = "*"
numpy = "*"
matplotlib = "*"
geopandas = "*"
pystac-client = "*"
odc-stac = "*"
xvec = "*"
xarray-spatial = "*"
datashader = "*"
planetary-computer = "*"
py3dep = "*"
pynhd = "*"
pygeoutils = "*"
ipyleaflet = "*"
ibis-duckdb = "*"
h3-py = "*"
folium = "*"
mapclassify = "*"
geoarrow-types = "*"
ipywidgets = "*"
lonboard = "*"
leafmap = "*"
# pmtiles = "*"
hvplot = "*"
holoviews = "*"
geoviews = "*"
bokeh = "*"
jupyter-cache = "*"
rasterio = ">=1.4.3,<2"
gdal = ">=3.10.0,<4"
movingpandas = ">=0.20.0,<0.21"
selenium = ">=4.27.1,<5"
# h5netcdf = ">=1.4.1,<2"
# dask = ">=2024.12.1,<2025"
# netcdf4 = ">=1.7.2,<2"
# bottleneck = ">=1.4.2,<2"
# zarr = ">=2.18.4,<3"
# earthengine-api = ">=1.4.3,<2"
# geemap = ">=0.35.1,<0.36"
# google-cloud-bigquery = ">=2.1.0,<3"
# fiona = ">=1.10.1,<2"
# seaborn = ">=0.13.2,<0.14"
# eemont = ">=0.3.6,<0.4"

[pypi-dependencies]
terrapyn = ">=0.3.0"
