[project]
name = "website"
description = "Colin Hill's personal website"
authors = ["Colin Hill <colinalastairhill@gmail.com>"]
channels = ["conda-forge"]
# linux-64 is used by GitHub Actions
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "==3.11"
jupyter = ">=1.1.1,<1.2"
numpy = ">=2.0.2,<2.1"
matplotlib = ">=3.9.2,<3.10"
geopandas = ">=1.0.1,<1.1"
pystac-client = ">=0.8.5,<0.9"
odc-stac = ">=0.3.10,<0.4"
xvec = ">=0.3.0,<0.4"
xarray-spatial = ">=0.4.0,<0.5"
datashader = ">=0.16.3,<0.17"
planetary-computer = ">=1.0.0,<1.1"
py3dep = ">=0.18.0,<0.19"
pynhd = ">=0.18.0,<0.19"
pygeoutils = ">=0.18.0,<0.19"
ipyleaflet = ">=0.19.2,<0.20"
ibis-duckdb = ">=9.5.0,<9.6"
h3-py = ">=4.1.1,<4.2"
folium = ">=0.18.0,<0.19"
mapclassify = ">=2.8.1,<2.9"
geoarrow-types = ">=0.2.0,<0.3"
ipywidgets = ">=8.1.5,<9"
lonboard = ">=0.10.3,<0.11"
leafmap = ">=0.40.1,<0.41"
pmtiles = ">=3.4.0,<4"
hvplot = ">=0.11.1,<0.12"
holoviews = ">=1.20.0,<2"
geoviews = ">=1.13.0,<2"
bokeh = ">=3.5.2,<4"
jupyter-cache = ">=1.0.1,<2"

[pypi-dependencies]
fused = "*" 
