[project]
name = "website"
description = "Colin Hill's personal website"
authors = ["Colin Hill <colinalastairhill@gmail.com>"]
channels = ["conda-forge"]
# linux-64 is used by GitHub Actions
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12"
jupyter = ">=1.1.1,<2"
numpy = "*"
matplotlib = "*"
geopandas = ">=1.0.1,<2"
pystac-client = ">=0.8.3,<0.9"
odc-stac = ">=0.3.10,<0.4"
xvec = ">=0.3.0,<0.4"
xarray-spatial = ">=0.4.0,<0.5"
datashader = ">=0.16.3,<0.17"
planetary-computer = ">=1.0.0,<2"
py3dep = ">=0.18.0,<0.19"
pynhd = ">=0.18.0,<0.19"
pygeoutils = ">=0.18.0,<0.19"
ipyleaflet = ">=0.19.2,<0.20"
