# on:
#   workflow_dispatch:
#   push:
#     branches: main

# name: Quarto Publish

# jobs:
#   build-deploy:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: write
#     steps:
#       - name: Check out repository
#         uses: actions/checkout@v4
#       - name: Set up Quarto
#         uses: quarto-dev/quarto-actions/setup@v2
#       - name: Setup pixi
#         uses: prefix-dev/setup-pixi@v0.8.1
#         with:
#           pixi-version: v0.30.0
#           activate-environment: true
#       - name: Render and Publish
#         uses: quarto-dev/quarto-actions/publish@v2
#         with:
#           target: gh-pages
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

